In [14]:
import argparse
import os
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow
import scipy.io
import scipy.misc
import numpy as np
import pandas as pd
import PIL
import tensorflow as tf
from keras import backend as K
from keras.layers import Input, Lambda, Conv2D
from keras.models import load_model, Model
from yolo_utils import read_classes, read_anchors, generate_colors, preprocess_image, draw_boxes, scale_boxes

In [1]:
import yad2k

In [2]:
a = np.random.randn(3, 5, 1)
b = np.random.randn(3, 5, 4)
c = a * b # shape of c will be (19*19, 5, 80)

Temp = np.max(c, axis=-1)
print(Temp.shape)
print(Temp)
print(c[0].shape)

(3, 5)
[[0.52947398 0.89673234 0.46166372 0.06453587 0.2700747 ]
 [0.02780277 0.01128318 0.22681943 1.97584957 0.3034983 ]
 [0.24766669 1.37082032 0.37215618 0.00349487 0.59175092]]
(5, 4)


In [3]:
box_confidence = tf.random_normal([19, 19, 5, 1], mean=1, stddev=4, seed = 1)
boxes = tf.random_normal([19, 19, 5, 4], mean=1, stddev=4, seed = 1)
box_class_probs = tf.random_normal([19, 19, 5, 80], mean=1, stddev=4, seed = 1)

scores = box_confidence*box_class_probs
print(scores[0][0][0])

Tensor("strided_slice_2:0", shape=(80,), dtype=float32)


In [135]:

with tf.Session() as test_a:
    maxval= K.max(scores, axis=-1)
    print(maxval.eval().shape)
    print(maxval[0][0].eval().shape)
    print(maxval[0][0].eval())
    print(maxval[1][18].eval())

(19, 19, 5)
(5,)
[87.99642  74.31815  30.659369 14.147522 10.937687]
[94.92611   8.038291 80.621666 14.513234 29.818005]


In [4]:
test = np.random.randn(1,10)

In [5]:
test

array([[-0.88305633,  2.76443108, -0.52657   ,  0.17201415, -0.35289461,
         0.36351858, -1.6148886 , -0.57724002, -0.07866482, -0.28779882]])

In [17]:
mask = test < 0.5

In [20]:
tensor = [0, 1, 2, 3]
mask = np.array([True, False, True, False])
np.boolean_mask(tensor, mask)  # [0, 2]

AttributeError: 'module' object has no attribute 'boolean_mask'